version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sanic-redis-ext-dev
    volumes:
      - ./:/app/
    tty: true

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
